Repository aniket8349/decoding_the_roads, pull requests merged in 2025-03, with the labels that each got.

#25 feat: added utility function convert sql_query (#13)
  decoding_the_roads/constant/constant.py
  decoding_the_roads/content/content.json
  decoding_the_roads/data_analysis/accidents_hotspot.py
  decoding_the_roads/data_analysis/accidents_year.py
  decoding_the_roads/data_analysis/common_causes.py
  decoding_the_roads/data_analysis/weather_condition.py
  decoding_the_roads/routers/pages_router.py
  decoding_the_roads/routers/sql_router.py
  decoding_the_roads/templates/components/chart.html
  decoding_the_roads/utils/csv_to_mysql.py
  decoding_the_roads/utils/logger.py
  decoding_the_roads/utils/read_json.py
  decoding_the_roads/utils/sql_utils.py
  decoding_the_roads/utils/sqlquery_to_json.py
  decoding_the_roads/utils/test_plot.py
  decoding_the_roads/visualizations/graph_pyplot.py
  tests/anote.py
Labels: enhancement, awaiting changes, awaiting merge, awaiting reviews

#27 fix: fixed kaggel issue which we faced inside issue : (#16)
  .gitignore
  Dockerfile
  README.md
  decoding_the_roads/config/db_config.py
  decoding_the_roads/config/kaggle_auth.py
  decoding_the_roads/main.py
  decoding_the_roads/utils/csv_to_mysql.py
Labels: awaiting merge, awaiting reviews, bug fix, refactor, chore

#31 Pages enhancements
  .github/workflows/deploy.yml
  decoding_the_roads/config/db_config.py
  decoding_the_roads/data_analysis/accidents_hotspot.py
  decoding_the_roads/data_analysis/accidents_year.py
  decoding_the_roads/data_analysis/common_causes.py
  decoding_the_roads/data_analysis/weather_condition.py
  decoding_the_roads/diagnostic_analysis/compaeative_analysis.py
  decoding_the_roads/diagnostic_analysis/eda.py
  decoding_the_roads/diagnostic_analysis/prediction.py
  decoding_the_roads/main.py
  decoding_the_roads/routers/pages_router.py
  decoding_the_roads/services/startup_event.py
  decoding_the_roads/utils/sqlquery_to_json.py
  decoding_the_roads/visualizations/graph_pyplot.py
  requirements.txt
  tests/test_api.py
  tests/test_main.py
Labels: enhancement, chore

#35 fix: port error
  decoding_the_roads/main.py
Labels: awaiting changes, chore

#38 chore: add env in gcloud run , deploy.yml
  .github/workflows/deploy.yml
  decoding_the_roads/routers/sql_router.py
Labels: awaiting changes, chore

#39 chore: fix workflow remove old images , deploy.yml
  .github/workflows/deploy.yml
Labels: awaiting merge, chore

#40 Fix workflow and remove old images
  .github/workflows/deploy.yml
Labels: awaiting merge, chore

#37 Feat: Prespective report(32)
  decoding_the_roads/data_analysis/descriptive_analysis/descriptive_report.py
  decoding_the_roads/data_analysis/prediction/prediction_report.py
  decoding_the_roads/diagnostic_analysis/compaeative_analysis.py
  decoding_the_roads/diagnostic_analysis/insight.py
  decoding_the_roads/diagnostic_analysis/prediction.py
  decoding_the_roads/diagnostic_analysis/prespective_report.py
Labels: enhancement

#41 Feature:Descriptive report
  requirements.txt
Labels: enhancement
